update mpvy

diff --git a/local/bin/mpvy b/local/bin/mpvy
--- a/local/bin/mpvy
+++ b/local/bin/mpvy
@@ -1,10 +1,26 @@
 #!/bin/bash -
-
 set -o nounset                                  # Treat unset variables as an error
-if [[ "$1" == "x" ]]; then
+
+mkdir -p "${HOME}/log"
+
+if [[ $# -eq 0 ]]; then
   echo "Usage: mpvy <playlist_id>"
+  exit 1
 else
-  #title=`youtube-dl --skip-download --get-title $1`
-  #mpv --no-video --term-playing-msg "### $title ###" $1
-  mpv --quiet --log-file=${HOME}/log/mpv_$(date +%Y%m%d_%H%M).log --no-video --shuffle --term-playing-msg='Title: ${media-title}' https://www.youtube.com/playlist\?list=${1}
+  playlist_id="$1"
+  playlist_url="https://www.youtube.com/playlist?list=${playlist_id}"
+
+  echo "Fetching playlist info..."
+  yt-dlp --flat-playlist --dump-json "$playlist_url" | jq -r '
+    .title as $title
+    | "[\(.playlist_index)] \(.title)"
+  ' || echo "⚠️ Failed to retrieve playlist info."
+  echo ""
+  echo "Playing... Press q to stop."
+  mpv --log-file=${HOME}/log/mpv_$(date +%Y%m%d_%H%M).log \
+      --no-video \
+      --shuffle \
+      --ytdl-format=bestaudio \
+      --script-opts=ytdl_hook-ytdl_path=yt-dlp \
+      --term-playing-msg='Title: ${media-title}' "$playlist_url"
 fi
